package it.unibo.msrehab.rl.model;

import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.function.Predicate;

/**
 * Controller to manage a collection of entities
 * @param <T> type of entities
 */
public interface IEntityController<T>
{
    /**
     * Creates a new entity. Subclasses of EntityManager can extend this method to provide additional
     * initialization
     *
     * @return a newly created entity. The entity is not inserted in the database
     */
    T newEntity();


    /**
     * Checks whether the controller contains any entity that matches the given predicate.
     *
     * @param predicate the condition to evaluate each entity against
     * @return true if at least one entity matches the predicate, false otherwise
     */
    boolean containsEntity(Predicate<T> predicate);

    /**
     * Checks if an entity with the specified identifier exists.
     *
     * @param id the identifier of the entity to be checked
     * @return true if the entity exists, false otherwise
     */
    boolean containsEntity(Object id);

    /**
     * Counts the total number of entities managed by the controller.
     *
     * @return the total number of entities currently managed
     */
    int countEntities();

    /**
     * Gets the entity with the specified identifier, or throw an exception if not found.
     *
     * @param id entity id
     * @return entity with the given id
     */
    default T getEntityOrThrow(Object id)
    {
        return findEntity(id).orElseThrow(() -> new IllegalArgumentException("Entity with id " + id + " not found"));
    }

    /**
     * Finds and retrieves an entity based on the given identifier.
     *
     * @param id the identifier of the entity to be retrieved
     * @return an {@code Optional} containing the retrieved entity if it exists, or an empty {@code Optional} if no entity is found
     */
    Optional<T> findEntity(Object id);

    /**
     * Finds and retrieves an entity that matches the specified predicate from the underlying collection.
     *
     * @param predicate the condition to evaluate each entity against for a match
     * @return an {@code Optional} containing the found entity if it exists, or an empty {@code Optional} if no match is found
     */
    Optional<T> findEntity(Predicate<T> predicate);

    /**
     * Retrieves all entities that satisfy the specified filter.
     *
     * @param filter the condition to evaluate each entity against, determining which entities
     *               to include in the result
     * @return a collection of entities that match the provided filter
     */
    Collection<T> getAllEntities(Predicate<T> filter);

    /**
     * Retrieves all entities managed by the controller.
     *
     * @return a collection of all entities managed by the controller
     */
    Collection<T> getAllEntities();

    /**
     * Checks whether the given entity is considered valid based on specific criteria.
     *
     * @param entity the entity to be validated
     * @return true if the entity is valid, false otherwise
     */
    boolean isEntityValid(T entity);

    /**
     * Groups entities based on a specified grouping function, applying an optional filter
     * to determine which entities should be included in the grouping.
     *
     * @param <G> the type of the group key the entities will be grouped by
     * @param filter a predicate used to filter entities before grouping; only entities
     *               that match the filter will be considered
     * @param groupingFunction a function that defines how to group the entities
     * @return a map where the keys represent group identifiers generated by the grouping
     *         function, and the values are lists of entities belonging to each group
     */
    <G> Map<G, List<T>> groupEntitiesBy(Predicate<T> filter, Function<T, G> groupingFunction);

    /**
     * Groups the entities managed by this controller based on the given grouping function.
     * Each group is represented by a key generated by the provided function, and the value is
     * a list of entities that correspond to that key.
     *
     * @param <G> the type of the grouping key
     * @param groupingFunction a function that determines the grouping key for each entity
     * @return a map where each key corresponds to a group and each value is a list of
     *         entities belonging to that group
     */
    <G> Map<G, List<T>> groupEntitiesBy(Function<T, G> groupingFunction);

    /**
     * Inserts the specified entity into the underlying storage or database.
     * The implementation may validate the entity before insertion.
     *
     * @param entity the entity to be inserted
     * @return true if the entity was successfully inserted, false otherwise
     */
    boolean insertEntity(T entity);

    /**
     * Inserts a new entity into the database. The provided entityBuilder is used
     * to initialize and define the entity before it is saved.
     *
     * @param entityBuilder a Consumer that initializes and customizes the entity
     *                      prior to its insertion into the database
     * @return the newly created and inserted entity
     */
    T insertEntity(Consumer<T> entityBuilder);

    /**
     * Inserts a collection of entities into the storage or database.
     * If at least one entity cannot be inserted, the operation is rolled back.
     *
     * @param entities the collection of entities to be inserted
     * @return true if all entities were successfully inserted, false otherwise
     */
    boolean insertEntities(Collection<T> entities);

    /**
     * Updates the entity identified by the given identifier using the specified updater function.
     * The updater function allows modifying the entity properties.
     *
     * @param id the identifier of the entity to be updated
     * @param updater a {@code Consumer} defining the modifications to be applied to the entity
     * @return true if the update was successful, false otherwise
     */
    boolean updateEntity(Object id, Consumer<T> updater);

    /**
     * Updates the specified entity in the underlying storage or database.
     * The implementation may validate the entity before updating it.
     *
     * @param entity the entity to be updated
     * @return true if the entity was successfully updated, false otherwise
     */
    boolean updateEntity(T entity);

    /**
     * Updates all entities that satisfy the given filter by applying the specified updater function.
     *
     * @param filter a predicate to determine which entities should be updated
     * @param updater a consumer that defines how to update the selected entities
     * @return true if the update was successful for all filtered entities, false otherwise
     */
    boolean updateEntities(Predicate<T> filter, Consumer<T> updater);

    /**
     * Updates a given collection of entities by applying the specified updater function to each entity.
     *
     * @param entities the collection of entities to be updated
     * @param updater a consumer that defines the update logic to apply to each entity
     * @return true if all entities in the collection were successfully updated, false otherwise
     */
    boolean updateEntities(Collection<T> entities, Consumer<T> updater);

    /**
     * Updates or replaces the specified entity in the underlying storage.
     * If the entity does not already exist, it is added to the storage.
     *
     * @param entity the entity to be updated or replaced in the storage
     * @return true if the operation was successful, false otherwise
     */
    boolean putEntity(T entity);

    /**
     * Replaces or inserts a collection of entities in the underlying storage.
     * If an entity already exists, it is updated; otherwise, it is added.
     *
     * @param entities the collection of entities to be inserted or updated
     * @return true if all entities were successfully processed, false otherwise
     */
    boolean putEntities(Collection<T> entities);

    /**
     * Updates the given collection of entities by applying changes to the underlying storage or database.
     * The operation ensures all entities in the collection are attempted to be updated.
     *
     * @param entities the collection of entities to be updated
     * @return true if all entities in the collection were successfully updated, false otherwise
     */
    boolean updateEntities(Collection<T> entities);

    /**
     * Removes an entity identified by the given identifier.
     *
     * @param id the identifier of the entity to be removed
     * @return true if the entity was successfully removed, false otherwise
     */
    boolean removeEntityWithId(Object id);

    /**
     * Removes the specified entity from the underlying storage or data source.
     *
     * @param entity the entity to be removed
     * @return true if the entity was successfully removed, false otherwise
     */
    boolean removeEntity(T entity);

    /**
     * Removes entities managed by the controller that satisfy the given predicate.
     * If at least one entitity is failed to be removed the whole transaction is rolled back
     * @param toRemovePredicate the condition to determine which entities should be removed
     * @return true if all entities matching the predicate were successfully removed, false otherwise
     */
    boolean removeEntities(Predicate<T> toRemovePredicate);

    /**
     * Removes a set of entities. If at least one entitity is failed to be removed the whole transaction is rolled back
     *
     * @param entities entitites to be removed from the stored ones
     * @return true if all entities were removed, false otherwise
     */
    boolean removeEntities(Collection<T> entities);
}
