package it.unibo.msrehab.rl.environment;


import it.unibo.msrehab.rl.common.StateTransition;

import java.util.List;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.stream.IntStream;


/**
 * Represents a generic environment interface for reinforcement learning tasks. This interface defines
 * core methods necessary for interacting with an environment, including resetting the environment,
 * advancing the environment using an action, retrieving the current state, and checking if the episode
 * is complete.
 * <p>
 * Important, S and A class should implement equals() and hashCode() methods to allow for comparison
 *
 * @param <S> The type representing the state of the environment.
 * @param <A> The type representing the actions that can be taken in the environment.
 */
public interface IEnvironment<S, A>
{
    StateTransition<S, A> reset();

    /**
     * Advances the environment by applying the given action and returns the resulting state transition.
     * This method simulates taking a single step in the environment by performing the specified action.
     *
     * @param action The action to be applied to the environment.
     * @return A {@code StateTransition<S, A>} object representing the transition result, including
     * the previous state, resulting state, action, reward, and whether the episode has ended.
     */
    StateTransition<S, A> step(A action);

    /**
     * Checks whether the current episode or task in the environment is complete.
     *
     * @return true if the environment indicates that the episode or task is finished; false otherwise.
     */
    boolean isDone();

    /**
     * Retrieves the current state of the environment.
     *
     * @return the current state of the environment.
     */
    S getState();

    /**
     * Plans a sequence of state transitions for a specified number of steps using the provided action selection strategy.
     * This method generates a list of state transitions by repeatedly applying the selected action
     * to the environment's current state.
     *
     * @param steps           The number of steps to plan. Specifies how many actions should be executed.
     * @param actionSelection A function that takes the current state of the environment as input and returns
     *                        the action to be performed at that state.
     * @return A list of {@code StateTransition<S, A>} objects representing the sequence of state transitions
     * generated by the planning process.
     */
    default List<StateTransition<S, A>> plan(int steps, Function<S, A> actionSelection)
    {
        return IntStream.range(0, steps)
                .mapToObj(s -> step(actionSelection.apply(getState())))
                .collect(Collectors.toList());
    }
}
